services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --prefer-binary -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    routes:
      - type: web
        source: /
        destination: fastapi-backend
        